import {
  ICredentialType,
  INodeProperties,
  ICredentialTestRequest,
  IAuthenticateGeneric,
} from "n8n-workflow";

import { GITHUB_COPILOT_API } from "../shared/utils/GitHubCopilotEndpoints";

/**
 * GitHub Copilot API Token Credentials
 * ONLY GitHub CLI generated tokens work with GitHub Copilot API
 * OAuth2 and Personal Access Tokens from GitHub website DO NOT work
 */

export class GitHubCopilotApi implements ICredentialType {
  name = "githubCopilotApi";

  displayName = "GitHub Copilot API (GitHub CLI Token)";

  documentationUrl =
    "https://docs.github.com/en/copilot/github-copilot-chat/copilot-chat-in-ides/using-github-copilot-chat-in-your-ide";

  properties: INodeProperties[] = [
    {
      displayName: "⚠️ IMPORTANT: GitHub CLI Token Required",
      name: "notice",
      type: "notice",
      default: "",
    },
    {
      displayName: "🚀 Easy Token Generation",
      name: "helperNotice",
      type: "notice",
      default: "Don't have GitHub CLI? Use our visual helper to get your token without terminal! Create a workflow with the 'GitHub Copilot Auth Helper' node, or access directly at your n8n instance.",
    },
    {
      displayName: "📖 How to Get Token",
      name: "instructionsNotice",
      type: "notice",
      default: "METHOD 1 (Visual): Use 'GitHub Copilot Auth Helper' node in n8n. METHOD 2 (CLI): Run 'gh auth login && gh auth token' in terminal. Only tokens starting with 'gho_' work with Copilot API.",
    },
    {
      displayName: "GitHub CLI Token",
      name: "token",
      type: "string",
      typeOptions: {
        password: true,
      },
      default: "",
      required: true,
      description:
				"⚠️ REQUIRED: Token generated by GitHub CLI that starts with \"gho_\". Get it by running: gh auth login && gh auth token. Other tokens will NOT work!",
      placeholder: "gho_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    },
  ];

  authenticate: IAuthenticateGeneric = {
    type: "generic",
    properties: {
      headers: {
        Authorization: "=Bearer {{$credentials.token}}",
        Accept: "application/json",
        "Content-Type": "application/json",
      },
    },
  };

  test: ICredentialTestRequest = {
    request: {
      baseURL: GITHUB_COPILOT_API.BASE_URL,
      url: GITHUB_COPILOT_API.ENDPOINTS.MODELS,
      method: "GET",
    },
  };
}
